GET http://localhost:8000/api/stock/products HTTP/1.1

###
POST http://localhost:8000/api/stock/products HTTP/1.1
Content-Type: application/json

{
  "productId": 1,
  "supplierId": 1,
  "amount": 100,
  "lotPrice": 230.55,
  "type": "ENTRY",
  "registredAt": "2024-04-01",
  "validUntil": "2024-06-01"
}