server:
  port: 8000
  error:
    include-stacktrace: never

spring:
  application:
    name: StockMicroSrvc
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce_stock
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    open-in-view: false
  sql:
    init:
      data-locations: classpath:data.sql
      mode: always
